name: Greeting
on: push
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello, World! From GitHub Actions"
      - name: Greet with Name
        run: echo "Hello, ${{ github.actor }}! From GitHub Actions"